### ISSUE TITLE
Build Mixmeter MVP

### ISSUE THREAD

**Issue by ghan** [thereplicants/max-node#2]
- [x] uses terms Meter and Duration
- [x] can change meter while performing
- [x] instead of playing every note in scale, only play held down notes in sequence
- [x] duration is changeable
- [x] Make duration tuplets that go up to 1, 2, 3, 4,  5, 6, 7, 8, 9, 10 beats too. So 10 9 8 .... 1 1/2 1/3 1/4 .... 1/9 1/10
- [x] Finish UI
- [x] has height dial that will extend the ascending arpeggio up octaves if the meter allows it
- [x] new control: mode[Touch, Ascend, Descend, Sine, Duosine]
- [x] Duosine controls
- [ ] Visualization
- [x] Rename to Duosine
- [x] Implement Humanize
- [x] Move Tuplet calc to Node

BUGS
- [x] if you hold down some notes, then increase the meter, it adds an empty note.
- [x] if you change Mode it doesn't update automatically
- [x] Works differently if in edit mode or in normal mode
- [x] tuplet is a value behind
- [x] Range seems a little wonky.. try it with Meter 30 and Range 7 or so
- [x] Tuplet doesn't seem to update while playing with it
- [ ] ASC and DESC modes broken with Range

**Comment by ghan** [comment]
@vine77 see below:

![Image](https://user-images.githubusercontent.com/12201837/183027849-5b8207bf-5d47-4a10-a666-c25831b5289e.png)

How do I save this change? it shows this stripe overlay which seems to signify an unsaved state but typical saving mechanisms don't seem to work.

**Comment by ghan** [comment]
https://github.com/thereplicants/max-node/pull/3

**Comment by vine77** [comment]
> How do I save this change? it shows this stripe overlay which seems to signify an unsaved state but typical saving mechanisms don't seem to work.

@ghan Can you be specific about what change exactly you want to save?

**Comment by vine77** [comment]
I may have found the issue you encountered... Just did some testing and found that you have to both save the change in the bpatcher window (the .max-pat file) then also save the main Max window (the .amxd file).

For example, if I wanted to force the dial to be a specific value when the Max patch loads, I can change that in the object inspector like this, then hit save in the .max-pat window then the main .amxd window.
![image](https://user-images.githubusercontent.com/175123/183144416-5e131386-d01a-4d06-8065-43c45279cfc4.png)

**Comment by vine77** [comment]
If the bpatcher is an annoying extra layer of abstraction, we can get rid of it and do everything in the main .amxd file. I just did it this way because I thought it might be nice for git to be able to track changes of the text-based .max-pat file since the .amxd is technically a binary file. (I guess the .amxd has a checksum embedded in it or something.)

**Comment by ghan** [comment]
oh interesting, I was just trying to change the label of the dial.

**Comment by ghan** [comment]
yup, that was it. I needed to save in both windows 🤦

**Comment by ghan** [comment]
@vine77 

I think there’s something about the way the patch loads normally (vs while editing) that I need to understand better… I have a bug that only presents itself if I’m not editing the patch
It might have to do with how I instantiate the control values…

I think it has to do with the bang message I've got in the middle there... maybe it doesn't fire when I play with it outside edit mode?

![Image](https://user-images.githubusercontent.com/12201837/184283423-9c39ea6e-f8e8-442a-a7b1-d1480a5b2227.png)
